DB_USERNAME = "vgudza"
DB_PASSWORD = "vgudza"
DB_HOST = "wb-go-team-dev.dev.wb.ru"
DB_NAME = "vgudza_shop"
NATS_HOSTS = "wbx-world-nats-stage.dp.wb.ru,wbx-world-nats-stage.dl.wb.ru"
NATS_CLUSTER_ID = "world-nats-stage"
NATS_CLIENT_ID = "vgudza"
NATS_SUBJECT = "go.test"
CACHE_SIZE = "10"
APP_KEY = "WB-1"